name: test_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  boxicons: ^2.1.3
  flutter_svg: ^2.0.7
  badges: ^3.1.1
  awesome_bottom_bar: ^1.2.2
  flutter_slidable: ^3.0.0
  flutter_native_splash: ^2.3.1
  top_snackbar_flutter: ^3.0.0+1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # device id
  android_id: ^0.2.0
  device_info_plus: ^9.0.2
  package_info_plus: ^4.0.2

  # for use api
  dio: ^5.2.1+1
  dio_cache_interceptor: ^3.4.2
  pretty_dio_logger: ^1.3.1
  # state management
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  # localisation
  easy_localization: ^3.0.2
  # di
  get_it: ^7.6.0
  injectable: ^2.1.2
  # json
  json_annotation: ^4.8.1
  # local db
  shared_preferences: ^2.2.0

    
# flutter_native_splash-development.yaml
flutter_native_splash:
  color: "#f0f3f5"
  image: asset/images/bell.png

  android_12:
    image: asset/images/bell.png

  web: false


#Run commands to generate splash screen
# 1. flutter clean
# 1. flutter pub get
# 1. flutter pub run flutter_native_splash:create

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2
  build_runner: ^2.4.6
  injectable_generator: ^2.1.6
  json_serializable: ^6.7.0

flutter:
  assets:
    - asset/env.secret
    - asset/images/
    - asset/translations/

  fonts:
    - family: Montserrat
      fonts:
        - asset: asset/fonts/Montserrat-Regular.ttf
        - asset: asset/fonts/Montserrat-Medium.ttf
        - asset: asset/fonts/Montserrat-SemiBold.ttf
    # - family: Trajan Pro
    #   fonts:
    #     - asset: fonts/TrajanPro.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700